# Stage 1: Build the Go application
FROM golang:1.23-bookworm AS build

# Add the entire bird app folder
ADD bird /app

# Set the working directory inside the container
WORKDIR /app

# This is commented out as there are "no module dependencies to download"
# Download go dependencies
#RUN go mod download

# Build the Go application
# CGO_ENABLED is for building without static linking
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 make

# Stage 2: Create a minimal final image for production
FROM alpine:latest

# Expose the port your service runs on
EXPOSE 4201

# Run app as nonroot user
USER 1001

#ENVs
ENV BIRDIMAGE_HOST=localhost
ENV BIRDIMAGE_PORT=4200

# Copy the binary from the build stage
COPY --from=build /app/getBird .

# Command to run the Go application
CMD [ "./getBird" ]
