---
apiVersion: v1
kind: Service
metadata:
  name: birdimage-service
  labels:
    app: birdimage
spec:
  selector:
    app: birdimage
  ports:
  - protocol: TCP
    port: 4200        # Service port
    targetPort: 4200  # Container port
  type: ClusterIP   # Change to LoadBalancer if you need external access