---
apiVersion: v1
kind: Service
metadata:
  name: bird-service
  labels:
    app: bird
spec:
  selector:
    app: bird
  ports:
  - protocol: TCP
    port: 4201        # Service port
    targetPort: 4201  # Container port
  type: ClusterIP   # Change to LoadBalancer if you need external access